/**
 * ⚠️ DEPRECATED: This file is auto-generated by Lovable's Supabase integration.
 * 
 * DO NOT USE THIS CLIENT IN NEW CODE.
 * 
 * MIGRATION NOTICE:
 * - This client is hardcoded to development Supabase (wkfgcroybuuefaulqsru)
 * - It does not respect environment variables
 * - It will be overwritten by future Lovable integration updates.
 * 
 * USE INSTEAD:
 * import { supabase } from '@/lib/supabase';
 * 
 * The primary client in src/lib/supabase.ts is environment-aware and
 * dynamically selects the correct Supabase project (Dev/Staging/Prod).
 * 
 * All imports of this deprecated client have been migrated to use
 * the primary client. This file remains only for reference and will
 * be regenerated by Lovable in future integration updates.
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://dqsegqxnnhowqjxifhej.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxc2VncXhubmhvd3FqeGlmaGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMzc1MzIsImV4cCI6MjA3NzgxMzUzMn0.hJKw731wyZHI8Py4LU0AgT2JKI5shenczB83jo4paT0';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
