// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lofjnaztnrlljtjaitph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZmpuYXp0bnJsbGp0amFpdHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzgxNTcsImV4cCI6MjA3MDY1NDE1N30.sgK7Afs6CRN7qXywmTHqKVMhj6RXMnstfBrPk_2TAYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});